### ISSUE TITLE
Input files for bspline

### ISSUE THREAD

**Issue by chburger** [qcscine/readuct#3]
The input for the bspline task is not clear to me.
If I concatenate the xyz coordinates of an educt and product into a file sz.xyz
and run the input file below, readuct stops with:

terminate called after throwing an instance of 'Scine::Utils::FormattedStreamHandler::FormatMismatchException'
  what():  The selected format and the provided stream do not match.
Aborted (core dumped)

systems:
- name: 'spline'
  path: 'sz.xyz'
  program: 'Turbomole'
  method_family: 'DFT'
  settings:
    molecular_charge: 0
    spin_multiplicity: 1
    method: 'PBE D3BJ'
    basis_set: 'def2-SVP'
tasks:
  - type: 'bspline'
    input: ['spline']
    output: ['spline_out']
    settings:
      extract_ts_guess: true

**Comment by steinmig** [comment]
You don't need to concatenate educt and product into a single xyz, rather each specified system in the input file should be a single structure. Therefore, you need to write two separate xyz files `educt.xyz` and `product.xyz`, then this input should do it:
```yaml
systems:
  - name: 'educt'
    path: 'educt.xyz'
    program: 'Turbomole'
    method_family: 'DFT'
    settings:
       molecular_charge: 0
       spin_multiplicity: 1
       method: 'PBE D3BJ'
       basis_set: 'def2-SVP'
  - name: 'product'
    path: 'product.xyz'
    program: 'Turbomole'
    method_family: 'DFT'
    settings:
       molecular_charge: 0
       spin_multiplicity: 1
       method: 'PBE D3BJ'
       basis_set: 'def2-SVP'
       
tasks:
  - type: 'bspline'
    input: ['educt', 'product']
    output: ['spline_out']
    settings:
        extract_ts_guess: true
```
However, when trying this out, I noticed we currently don't support a technicality to allow turbomole for b-spline optimizations. If this would be an option, you could switch to Orca (change `Turbomole` to `Orca` and before executing readuct, call `export ORCA_BINARY_PATH=/path/to/orca/binary`), otherwise this technicality should be included in the next release.
